# Explanation:
Static Data:
The data dictionary contains a dataset with features such as name, age, salary, city, and experience.

Initialization:
The FeatureEngineer class initializes with the DataFrame created from the static data.

Creating New Features:
The create_new_features method creates new features like age_group by binning ages and salary_per_year_experience by calculating salary per year of experience.

Encoding Categorical Variables:
The encode_categorical_variables method applies Label Encoding to the city column and One-Hot Encoding to the age_group column.

Binning:
The binning method bins the salary column into 3 uniform bins.

Polynomial Features:
The polynomial_features method creates polynomial features for age and experience.

Demonstration:
The script demonstrates each technique by applying them to the DataFrame and printing the results.
This script can be run in a Python environment to see the different feature engineering techniques in action.

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.preprocessing import PolynomialFeatures

# Define static data
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'age': [25, 32, 45, 28, 34],
    'salary': [50000, 60000, 80000, 45000, 70000],
    'city': ['New York', 'Los Angeles', 'New York', 'Chicago', 'Los Angeles'],
    'experience': [2, 7, 10, 4, 6]
}

# Convert static data to DataFrame
df = pd.DataFrame(data)

# Define the feature engineering class
class FeatureEngineer:
    def __init__(self, dataframe):
        self.df = dataframe
    
    def create_new_features(self):
        # Create new features such as age groups
        self.df['age_group'] = pd.cut(self.df['age'], bins=[0, 25, 35, 50], labels=['Young', 'Adult', 'Senior'])
        
        # Create interaction features
        self.df['salary_per_year_experience'] = self.df['salary'] / self.df['experience']
        return self.df
    
    def encode_categorical_variables(self):
        # Label Encoding for 'city'
        label_encoder = LabelEncoder()
        self.df['city_encoded'] = label_encoder.fit_transform(self.df['city'])
        
        # One Hot Encoding for 'age_group'
        one_hot_encoder = OneHotEncoder(sparse=False, drop='first')
        age_group_encoded = one_hot_encoder.fit_transform(self.df[['age_group']])
        age_group_encoded_df = pd.DataFrame(age_group_encoded, columns=one_hot_encoder.get_feature_names_out(['age_group']))
        
        self.df = pd.concat([self.df, age_group_encoded_df], axis=1)
        return self.df
    
    def binning(self):
        # Binning 'salary' into 3 bins
        binning = KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='uniform')
        self.df['salary_binned'] = binning.fit_transform(self.df[['salary']])
        return self.df
    
    def polynomial_features(self):
        # Create polynomial features
        poly = PolynomialFeatures(degree=2, include_bias=False)
        poly_features = poly.fit_transform(self.df[['age', 'experience']])
        poly_features_df = pd.DataFrame(poly_features, columns=poly.get_feature_names_out(['age', 'experience']))
        
        self.df = pd.concat([self.df, poly_features_df], axis=1)
        return self.df

# Initialize the feature engineer
engineer = FeatureEngineer(df.copy())

# Demonstrate different feature engineering techniques
print("Original DataFrame:")
print(df, "\n")

# Creating new features
print("After creating new features:")
print(engineer.create_new_features(), "\n")

# Encoding categorical variables
engineer = FeatureEngineer(df.copy())  # Reset to original data
print("After encoding categorical variables:")
print(engineer.create_new_features())  # Include newly created features before encoding
print(engineer.encode_categorical_variables(), "\n")

# Binning
engineer = FeatureEngineer(df.copy())  # Reset to original data
print("After binning:")
print(engineer.create_new_features())  # Include newly created features before binning
print(engineer.binning(), "\n")

# Polynomial features
engineer = FeatureEngineer(df.copy())  # Reset to original data
print("After creating polynomial features:")
print(engineer.polynomial_features(), "\n")

Original DataFrame:
      name  age  salary         city  experience
0    Alice   25   50000     New York           2
1      Bob   32   60000  Los Angeles           7
2  Charlie   45   80000     New York          10
3    David   28   45000      Chicago           4
4      Eva   34   70000  Los Angeles           6

After creating new features:
      name  age  salary         city  experience age_group  \
0    Alice   25   50000     New York           2     Young
1      Bob   32   60000  Los Angeles           7     Adult
2  Charlie   45   80000     New York          10    Senior
3    David   28   45000      Chicago           4     Adult
4      Eva   34   70000  Los Angeles           6     Adult

   salary_per_year_experience
0                25000.000000
1                 8571.428571
2                 8000.000000
3                11250.000000
4                11666.666667

After encoding categorical variables:
      name  age  salary         city  experience age_group  \
0    Alice   25   50000     New York           2     Young
1      Bob   32   60000  Los Angeles           7     Adult
2  Charlie   45   80000     New York          10    Senior
3    David   28   45000      Chicago           4     Adult
4      Eva   34   70000  Los Angeles           6     Adult

   salary_per_year_experience
0                25000.000000
1                 8571.428571
2                 8000.000000
3                11250.000000
4                11666.666667
      name  age  salary         city  experience age_group  \
0    Alice   25   50000     New York           2     Young
1      Bob   32   60000  Los Angeles           7     Adult
2  Charlie   45   80000     New York          10    Senior
3    David   28   45000      Chicago           4     Adult
4      Eva   34   70000  Los Angeles           6     Adult

   salary_per_year_experience  city_encoded  age_group_Senior  age_group_Young
0                25000.000000             2               0.0              1.0
1                 8571.428571             1               0.0              0.0
2                 8000.000000             2               1.0              0.0
3                11250.000000             0               0.0              0.0
4                11666.666667             1               0.0              0.0

After binning:
      name  age  salary         city  experience age_group  \
0    Alice   25   50000     New York           2     Young
1      Bob   32   60000  Los Angeles           7     Adult
2  Charlie   45   80000     New York          10    Senior
3    David   28   45000      Chicago           4     Adult
4      Eva   34   70000  Los Angeles           6     Adult

   salary_per_year_experience
0                25000.000000
1                 8571.428571
2                 8000.000000
3                11250.000000
4                11666.666667
      name  age  salary         city  experience age_group  \
0    Alice   25   50000     New York           2     Young
1      Bob   32   60000  Los Angeles           7     Adult
2  Charlie   45   80000     New York          10    Senior
3    David   28   45000      Chicago           4     Adult
4      Eva   34   70000  Los Angeles           6     Adult

   salary_per_year_experience  salary_binned
0                25000.000000            0.0
1                 8571.428571            1.0
2                 8000.000000            2.0
3                11250.000000            0.0
4                11666.666667            2.0

After creating polynomial features:
      name  age  salary         city  experience   age  experience   age^2  \
0    Alice   25   50000     New York           2  25.0         2.0   625.0
1      Bob   32   60000  Los Angeles           7  32.0         7.0  1024.0
2  Charlie   45   80000     New York          10  45.0        10.0  2025.0
3    David   28   45000      Chicago           4  28.0         4.0   784.0
4      Eva   34   70000  Los Angeles           6  34.0         6.0  1156.0

   age experience  experience^2
0            50.0           4.0
1           224.0          49.0
2           450.0         100.0
3           112.0          16.0
4           204.0          36.0

F:\anaconda\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
F:\anaconda\Lib\site-packages\sklearn\preprocessing\_discretization.py:239: FutureWarning: In version 1.5 onwards, subsample=200_000 will be used by default. Set subsample explicitly to silence this warning in the mean time. Set subsample=None to disable subsampling explicitly.
  warnings.warn(